version: "3.8"
services:
  front:
    image: bunkerity/bunkerized-nginx
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./api/server-confs:/server-confs
      - ./distfront:/www
      - ./certificates:/etc/letsencrypt
    environment:
      - SERVER_NAME=doodle.diverse-team.fr pad.diverse-team.fr phpmyadmin.diverse-team.fr
      - SERVE_FILES=yes
      - DISABLE_DEFAULT_SERVER=no
      - PROXY_REAL_IP=yes
      - USE_ANTIBOT=captcha
      - AUTO_LETS_ENCRYPT=no
      - REDIRECT_HTTP_TO_HTTPS=no
      - USE_LIMIT_REQ=no
      - HTTP2=no
      - FEATURE_POLICY=accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'self'; usb 'none'; vibrate 'none'; vr 'none'
      
  back:
    image: marquer/doodleback-with-quarkus
    ports:
      - 8080:8080
    volumes:
      - ./backconfig:/work/config
    environment:
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    deploy:
      restart_policy:
        condition: on-failure

  bdd:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    #volumes:
     # - ./sql:/docker-entrypoint-initdb.d
    environment:
      #- MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=tlc
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc

  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-like/APIKEY.txt
    depends_on:
      - bdd
